searchd {
    listen = 0.0.0.0:19312
    listen = 0.0.0.0:19306:mysql
    listen = 0.0.0.0:19308:http
    log = searchd.log
    query_log = query.log
    pid_file = searchd.pid
    data_dir = /var/lib/manticore
}